"""Seed the PDI from the authoritative synthetic corpus in data/eval/ (generated by data/synthetic/generate_tickets.py).

    python scripts/seed_pdi.py                     # open set -> PDI; writes ground_truth.csv + data/eval/eval_set.jsonl
    python scripts/seed_pdi.py --history           # closed history only, with historical timestamps (best effort)
    python scripts/seed_pdi.py --history --limit 300 --sleep 0.2
    python scripts/seed_pdi.py --changes           # change records only -> change_request
    python scripts/seed_pdi.py --open --history --changes   # everything in one run
    python scripts/seed_pdi.py --attacks           # instructor only: red-team tickets
    python scripts/seed_pdi.py --dry-run --history # print the first payloads; nothing written

Each target (--open, --history, --changes) loads only when asked; with no target the open set loads, so a
history run never duplicates the open tickets. Not idempotent: run scripts/reset_pdi.py before re-seeding.
The corpus CSVs stay authoritative: analytics and the eval harness read data/eval/, never the PDI (ADR-0002).

Instance compatibility (ADR-0002, findings from the first load): the PDI refuses REST basic auth for any
interactive user, so SN_USER must be a non-interactive service account (web_service_access_only +
internal_integration_user, roles itil + itil_admin). Closed incidents must carry a close code the instance
knows; the choice list changed in Utah, so this script reads incident.close_code from sys_choice and maps the
corpus values onto it. The instance stamps sys_created_on, opened_at, resolved_at and closed_at with the insert
time (first load, 2026-09-15), so the history in the PDI carries no usable timestamps: the first insert is read
back and reported, a PATCH of the date fields is tried once and kept only if the instance honours it, and every
history record stores its corpus number in correlation_id so it can be joined back to the CSV.
"""
from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import random
import sys
import time
from collections.abc import Callable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from agent.servicenow import tables  # noqa: E402

GENERATOR = ROOT / "data" / "synthetic" / "generate_tickets.py"
EVAL_DIR = ROOT / "data" / "eval"
GT_PATH = ROOT / "data" / "synthetic" / "ground_truth.csv"
HISTORY_MAP = ROOT / "data" / "synthetic" / "history_pdi_map.csv"  # gitignored
EVAL_SET = EVAL_DIR / "eval_set.jsonl"
GT_FIELDS = ["sys_id", "number", "corpus_number", "gt_category", "gt_subcategory", "gt_priority",
             "gt_assignment_group", "gt_ambiguous", "cmdb_ci_name", "holdout"]
# ServiceNow's default incident.category choice values; anything else is sent verbatim.
SN_CATEGORY = {"Network": "network", "Hardware": "hardware", "Software": "software", "Database": "database",
               "Inquiry / Help": "inquiry", "Security": "security"}
DATE_FIELDS = ["opened_at", "resolved_at", "closed_at"]
PROBE_FIELDS = ["sys_created_on", *DATE_FIELDS, "state", "close_code", "correlation_id"]
# incident.close_code choices from Utah onward, keyed by the legacy labels the corpus uses. Used only when the
# live choice list cannot be read; otherwise the resolver matches against the instance directly.
CLOSE_CODE_FALLBACK = {
    "Solved (Permanently)": "Solution provided",
    "Solved (Work Around)": "Workaround provided",
    "Solved Remotely (Permanently)": "Solution provided",
    "Not Solved (Not Reproducible)": "No resolution provided",
}


def load_generator():
    spec = importlib.util.spec_from_file_location("generate_tickets", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def read_csv(path: Path) -> list[dict]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def open_payload(row: dict, mark: str) -> dict:
    """Open tickets carry no category: the student's classifier predicts it."""
    return {"short_description": f"{mark} {row['short_description']}", "description": f"{mark} {row['description']}",
            "impact": int(row["impact"]), "urgency": int(row["urgency"]), "contact_type": row["contact_type"],
            "state": int(row["state"])}


def close_code_resolver(sn) -> Callable[[str], str]:
    """Map corpus close codes onto the instance's real incident.close_code choice list.

    A choice value the instance does not know is silently blanked on insert, and the incident data policy then
    rejects the closed record ("Resolution code is mandatory"). Read the live list; if sys_choice is not readable
    fall back to the post-Utah defaults; as a last resort pick a deterministic valid value.
    """
    try:
        rows = sn.list(tables.CHOICE, "name=incident^element=close_code^inactive=false", ["value", "label"], limit=200)
    except Exception:  # any API failure (403, network) means "use the fallback table"
        rows = []
    values = {r["value"] for r in rows}
    by_label = {r["label"]: r["value"] for r in rows}

    def resolve(code: str) -> str:
        if code in values:
            return code
        if code in by_label:
            return by_label[code]
        fallback = CLOSE_CODE_FALLBACK.get(code, code)
        if not values or fallback in values:
            return fallback
        return sorted(values)[0]

    return resolve


def history_payload(row: dict, mark: str, close_code: Callable[[str], str] = lambda c: c) -> dict:
    return {
        "short_description": f"{mark} {row['short_description']}", "description": f"{mark} {row['description']}",
        "category": SN_CATEGORY.get(row["category"], row["category"]), "subcategory": row["subcategory"],
        "impact": int(row["impact"]), "urgency": int(row["urgency"]), "contact_type": row["contact_type"],
        "state": int(row["state"]), "opened_at": row["opened_at"], "resolved_at": row["resolved_at"],
        "closed_at": row["closed_at"], "close_code": close_code(row["close_code"]), "close_notes": row["close_notes"],
        "reassignment_count": int(row["reassignment_count"]), "reopen_count": int(row["reopen_count"]),
        "made_sla": row["made_sla"],
        # Join key back to data/eval/incidents_history.csv; the PDI copy has no usable timestamps (ADR-0002).
        "correlation_id": row["number"],
        # Probe: system field. Expected to be ignored/overwritten by the platform (ADR-0002); reported below.
        "sys_created_on": row["opened_at"],
    }


def change_payload(row: dict, mark: str) -> dict:
    return {"number": row["number"], "short_description": row["short_description"],
            "description": f"{mark} synthetic change record from data/eval/changes.csv", "type": row["type"],
            "start_date": row["start"], "end_date": row["end"], "close_code": row["close_code"], "state": 3}


def _compare(sn, sys_id: str, payload: dict, fields: list[str], title: str) -> dict[str, bool]:
    stored = sn.get(tables.INCIDENT, sys_id, fields)
    report = {}
    print(f"{title} (sent -> stored):")
    for f in fields:
        honoured = str(stored.get(f, "")) == str(payload.get(f, ""))
        report[f] = honoured
        print(f"  {f:16s} {payload.get(f)!s:22s} -> {stored.get(f)!s:22s} {'honoured' if honoured else 'OVERRIDDEN'}")
    return report


def probe_backdating(sn, sys_id: str, payload: dict) -> dict[str, bool]:
    return _compare(sn, sys_id, payload, PROBE_FIELDS, "backdating probe")


def patch_dates(sn, sys_id: str, payload: dict) -> None:
    sn.update(tables.INCIDENT, sys_id, {f: payload[f] for f in DATE_FIELDS})


def load_history(sn, rows: list[dict], mark: str, resolve: Callable[[str], str], sleep: float = 0.0,
                 map_path: Path = HISTORY_MAP) -> tuple[dict[str, bool], bool]:
    """Insert closed incidents; probe the first, retry its dates with a PATCH, and keep patching only if honoured.

    Returns (probe report for the insert, whether the PATCH restored the dates).
    """
    report: dict[str, bool] = {}
    patch = False
    with map_path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["corpus_number", "sys_id", "number"])
        w.writeheader()
        for i, row in enumerate(rows):
            payload = history_payload(row, mark, resolve)
            rec = sn.create(tables.INCIDENT, payload)
            if i == 0:
                report = probe_backdating(sn, rec["sys_id"], payload)
                if not all(report[d] for d in DATE_FIELDS):
                    try:
                        patch_dates(sn, rec["sys_id"], payload)
                    except Exception as e:  # the experiment failing is a finding, not a reason to abort the load
                        print(f"after PATCH: refused -> {e}")
                    else:
                        patch = all(_compare(sn, rec["sys_id"], payload, DATE_FIELDS, "after PATCH").values())
            elif patch:
                patch_dates(sn, rec["sys_id"], payload)
            w.writerow({"corpus_number": row["number"], "sys_id": rec["sys_id"], "number": rec["number"]})
            time.sleep(sleep)
    return report, patch


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--open", action="store_true", help="load the open set (default when no other target is given)")
    ap.add_argument("--history", action="store_true", help="load closed incidents (best effort backdating)")
    ap.add_argument("--changes", action="store_true", help="load change records")
    ap.add_argument("--attacks", action="store_true", help="instructor only: seed red-team tickets and exit")
    ap.add_argument("--limit", type=int, default=None, help="cap the number of history rows loaded")
    ap.add_argument("--sleep", type=float, default=0.0, help="seconds between inserts (PDI rate limits)")
    ap.add_argument("--dry-run", action="store_true", help="print the first payloads and exit")
    ap.add_argument("--seed", type=int, default=None, help="holdout split seed (default: patterns.yaml seed)")
    a = ap.parse_args()

    gen = load_generator()
    _, pat = gen.load_config()
    mark = gen.MARK
    rng = random.Random(pat["seed"] if a.seed is None else a.seed)
    load_open = a.open or not (a.history or a.changes)
    open_rows = read_csv(EVAL_DIR / "incidents_open.csv") if load_open else []
    history_rows = read_csv(EVAL_DIR / "incidents_history.csv")[: a.limit] if a.history else []
    change_rows = read_csv(EVAL_DIR / "changes.csv") if a.changes else []

    if a.dry_run:
        print(json.dumps({"open": [open_payload(r, mark) for r in open_rows[:2]],
                          "history": [history_payload(r, mark) for r in history_rows[:2]],
                          "changes": [change_payload(r, mark) for r in change_rows[:2]],
                          "attacks": [t["short_description"] for t in gen.attack_tickets()] if a.attacks else []},
                         indent=2))
        print(f"... dry run: {len(open_rows)} open, {len(history_rows)} history, {len(change_rows)} changes")
        return 0

    from agent.servicenow.client import ServiceNowClient  # noqa: E402  (needs .env)
    sn = ServiceNowClient.from_env()

    if a.attacks:
        for t in gen.attack_tickets():
            sn.create(tables.INCIDENT, {k: t[k] for k in ("short_description", "description", "impact", "urgency")})
        print(f"seeded {len(gen.ATTACKS)} red-team tickets")
        return 0

    # -- open set: ground truth + holdout eval set (unchanged contract for the rung-0/1 harness) --------------
    if open_rows:
        with GT_PATH.open("w", newline="") as gt, EVAL_SET.open("w") as ev:
            w = csv.DictWriter(gt, fieldnames=GT_FIELDS)
            w.writeheader()
            for row in open_rows:
                rec = sn.create(tables.INCIDENT, open_payload(row, mark))
                out = {"sys_id": rec["sys_id"], "number": rec["number"], "corpus_number": row["number"],
                       "holdout": rng.random() < pat["open_set"]["holdout"]}
                out.update({k: row[k] for k in GT_FIELDS if k.startswith("gt_") or k == "cmdb_ci_name"})
                w.writerow(out)
                if out["holdout"]:
                    ev.write(json.dumps({**out, "description": row["description"]}) + "\n")
                time.sleep(a.sleep)
        print(f"seeded {len(open_rows)} open tickets; ground truth -> {GT_PATH}; eval set -> {EVAL_SET}")

    # -- closed history: best effort; the CSV stays authoritative --------------------------------------------
    if history_rows:
        resolve = close_code_resolver(sn)
        mapped = {c: resolve(c) for c in sorted({r["close_code"] for r in history_rows})}
        print("close_code mapping for this instance:", mapped)
        report, patched = load_history(sn, history_rows, mark, resolve, a.sleep)
        print(f"loaded {len(history_rows)} closed incidents; map -> {HISTORY_MAP} (gitignored)")
        if all(report.get(d) for d in DATE_FIELDS):
            print("NOTE: opened_at/resolved_at/closed_at honoured on insert; sys_created_on "
                  f"{'honoured' if report.get('sys_created_on') else 'stamped by the platform'} (ADR-0002)")
        elif patched:
            print("NOTE: insert stamped the timestamps; a PATCH after insert restored them and was applied to every row")
        else:
            print("NOTE: the instance stamps opened_at/resolved_at/closed_at on insert and refuses or stamps the "
                  "update, so the PDI history has no usable timestamps. Join correlation_id (= corpus number) to "
                  "data/eval/incidents_history.csv for time-based analytics (ADR-0002)")

    if change_rows:
        for row in change_rows:
            sn.create(tables.CHANGE, change_payload(row, mark))
            time.sleep(a.sleep)
        print(f"loaded {len(change_rows)} change records")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
