"""Seed the PDI from the authoritative synthetic corpus in data/eval/ (generated by data/synthetic/generate_tickets.py).

    python scripts/seed_pdi.py                     # open set -> PDI; writes ground_truth.csv + data/eval/eval_set.jsonl
    python scripts/seed_pdi.py --history           # also load the closed history with historical timestamps (best effort)
    python scripts/seed_pdi.py --history --limit 300 --sleep 0.2
    python scripts/seed_pdi.py --changes           # change records -> change_request
    python scripts/seed_pdi.py --attacks           # instructor only: red-team tickets
    python scripts/seed_pdi.py --dry-run --history # print the first payloads; nothing written

Idempotent only after scripts/reset_pdi.py. The corpus CSVs stay authoritative: analytics and the eval harness
read data/eval/, never the PDI (ADR-0002). ServiceNow protects sys_created_on on insert, so history rows carry
their true timestamps in opened_at / resolved_at / closed_at; this script probes the first insert and reports
which timestamp fields the instance honoured.
"""
from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import random
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from agent.servicenow import tables  # noqa: E402

GENERATOR = ROOT / "data" / "synthetic" / "generate_tickets.py"
EVAL_DIR = ROOT / "data" / "eval"
GT_PATH = ROOT / "data" / "synthetic" / "ground_truth.csv"
HISTORY_MAP = ROOT / "data" / "synthetic" / "history_pdi_map.csv"  # gitignored
EVAL_SET = EVAL_DIR / "eval_set.jsonl"
GT_FIELDS = ["sys_id", "number", "corpus_number", "gt_category", "gt_subcategory", "gt_priority",
             "gt_assignment_group", "gt_ambiguous", "cmdb_ci_name", "holdout"]
# ServiceNow's default incident.category choice values; anything else is sent verbatim.
SN_CATEGORY = {"Network": "network", "Hardware": "hardware", "Software": "software", "Database": "database",
               "Inquiry / Help": "inquiry", "Security": "security"}
PROBE_FIELDS = ["sys_created_on", "opened_at", "resolved_at", "closed_at", "state"]


def load_generator():
    spec = importlib.util.spec_from_file_location("generate_tickets", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def read_csv(path: Path) -> list[dict]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def open_payload(row: dict, mark: str) -> dict:
    """Open tickets carry no category: the student's classifier predicts it."""
    return {"short_description": f"{mark} {row['short_description']}", "description": f"{mark} {row['description']}",
            "impact": int(row["impact"]), "urgency": int(row["urgency"]), "contact_type": row["contact_type"],
            "state": int(row["state"])}


def history_payload(row: dict, mark: str) -> dict:
    return {
        "short_description": f"{mark} {row['short_description']}", "description": f"{mark} {row['description']}",
        "category": SN_CATEGORY.get(row["category"], row["category"]), "subcategory": row["subcategory"],
        "impact": int(row["impact"]), "urgency": int(row["urgency"]), "contact_type": row["contact_type"],
        "state": int(row["state"]), "opened_at": row["opened_at"], "resolved_at": row["resolved_at"],
        "closed_at": row["closed_at"], "close_code": row["close_code"], "close_notes": row["close_notes"],
        "reassignment_count": int(row["reassignment_count"]), "reopen_count": int(row["reopen_count"]),
        "made_sla": row["made_sla"],
        # Probe: system field. Expected to be ignored/overwritten by the platform (ADR-0002); reported below.
        "sys_created_on": row["opened_at"],
    }


def change_payload(row: dict, mark: str) -> dict:
    return {"number": row["number"], "short_description": row["short_description"],
            "description": f"{mark} synthetic change record from data/eval/changes.csv", "type": row["type"],
            "start_date": row["start"], "end_date": row["end"], "close_code": row["close_code"], "state": 3}


def probe_backdating(sn, sys_id: str, payload: dict) -> dict[str, bool]:
    stored = sn.get(tables.INCIDENT, sys_id, PROBE_FIELDS)
    report = {}
    print("backdating probe (sent -> stored):")
    for f in PROBE_FIELDS:
        honoured = str(stored.get(f, "")) == str(payload.get(f, ""))
        report[f] = honoured
        print(f"  {f:16s} {payload.get(f)!s:22s} -> {stored.get(f)!s:22s} {'honoured' if honoured else 'OVERRIDDEN'}")
    return report


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--history", action="store_true", help="also load closed incidents (best effort backdating)")
    ap.add_argument("--changes", action="store_true", help="load change records")
    ap.add_argument("--attacks", action="store_true", help="instructor only: seed red-team tickets and exit")
    ap.add_argument("--limit", type=int, default=None, help="cap the number of history rows loaded")
    ap.add_argument("--sleep", type=float, default=0.0, help="seconds between inserts (PDI rate limits)")
    ap.add_argument("--dry-run", action="store_true", help="print the first payloads and exit")
    ap.add_argument("--seed", type=int, default=None, help="holdout split seed (default: patterns.yaml seed)")
    a = ap.parse_args()

    gen = load_generator()
    _, pat = gen.load_config()
    mark = gen.MARK
    rng = random.Random(pat["seed"] if a.seed is None else a.seed)
    open_rows = read_csv(EVAL_DIR / "incidents_open.csv")
    history_rows = read_csv(EVAL_DIR / "incidents_history.csv")[: a.limit] if a.history else []
    change_rows = read_csv(EVAL_DIR / "changes.csv") if a.changes else []

    if a.dry_run:
        print(json.dumps({"open": [open_payload(r, mark) for r in open_rows[:2]],
                          "history": [history_payload(r, mark) for r in history_rows[:2]],
                          "changes": [change_payload(r, mark) for r in change_rows[:2]],
                          "attacks": [t["short_description"] for t in gen.attack_tickets()] if a.attacks else []},
                         indent=2))
        print(f"... dry run: {len(open_rows)} open, {len(history_rows)} history, {len(change_rows)} changes")
        return 0

    from agent.servicenow.client import ServiceNowClient  # noqa: E402  (needs .env)
    sn = ServiceNowClient.from_env()

    if a.attacks:
        for t in gen.attack_tickets():
            sn.create(tables.INCIDENT, {k: t[k] for k in ("short_description", "description", "impact", "urgency")})
        print(f"seeded {len(gen.ATTACKS)} red-team tickets")
        return 0

    # -- open set: ground truth + holdout eval set (unchanged contract for the rung-0/1 harness) --------------
    with GT_PATH.open("w", newline="") as gt, EVAL_SET.open("w") as ev:
        w = csv.DictWriter(gt, fieldnames=GT_FIELDS)
        w.writeheader()
        for row in open_rows:
            rec = sn.create(tables.INCIDENT, open_payload(row, mark))
            out = {"sys_id": rec["sys_id"], "number": rec["number"], "corpus_number": row["number"],
                   "holdout": rng.random() < pat["open_set"]["holdout"]}
            out.update({k: row[k] for k in GT_FIELDS if k.startswith("gt_") or k == "cmdb_ci_name"})
            w.writerow(out)
            if out["holdout"]:
                ev.write(json.dumps({**out, "description": row["description"]}) + "\n")
            time.sleep(a.sleep)
    print(f"seeded {len(open_rows)} open tickets; ground truth -> {GT_PATH}; eval set -> {EVAL_SET}")

    # -- closed history: best effort; the CSV stays authoritative --------------------------------------------
    if history_rows:
        report: dict[str, bool] = {}
        with HISTORY_MAP.open("w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=["corpus_number", "sys_id", "number"])
            w.writeheader()
            for i, row in enumerate(history_rows):
                payload = history_payload(row, mark)
                rec = sn.create(tables.INCIDENT, payload)
                if i == 0:
                    report = probe_backdating(sn, rec["sys_id"], payload)
                w.writerow({"corpus_number": row["number"], "sys_id": rec["sys_id"], "number": rec["number"]})
                time.sleep(a.sleep)
        print(f"loaded {len(history_rows)} closed incidents; map -> {HISTORY_MAP} (gitignored)")
        if not report.get("sys_created_on"):
            print("NOTE: sys_created_on was not honoured; analytics must key on opened_at (see ADR-0002)")

    if change_rows:
        for row in change_rows:
            sn.create(tables.CHANGE, change_payload(row, mark))
            time.sleep(a.sleep)
        print(f"loaded {len(change_rows)} change records")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
